In [6]:
import pandas as pd
data = pd.read_csv(r"C:\Users\timas\Downloads\RSV_statistics_hour_31012023_31012023.csv", encoding='Macintosh', delimiter=';')
data.head()

,◊‡Ò,"Œ·˙ÂÏ ÔÓÎÌÓ„Ó ÔÎ‡ÌÓ‚Ó„Ó ÔÓÚÂ·ÎÂÌËˇ, Ã¬Ú.˜","»Ì‰ÂÍÒ ‡‚ÌÓ‚ÂÒÌ˚ı ˆÂÌ Ì‡ ÔÓÍÛÔÍÛ ˝ÎÂÍÚÓ˝ÌÂ„ËË, Û·./Ã¬Ú.˜.","Œ·˙ÂÏ ÔÓÍÛÔÍË ÔÓ Â„ÛÎËÛÂÏ˚Ï ‰Ó„Ó‚Ó‡Ï, Ã¬Ú.˜","Œ·˙ÂÏ ÔÓÍÛÔÍË Ì‡ –—¬, Ã¬Ú.˜","Œ·˙ÂÏ ÔÓ‰‡ÊË ‚ Ó·ÂÒÔÂ˜ÂÌËÂ –ƒ, Ã¬Ú.˜","Ã‡ÍÒËÏ‡Î¸Ì˚È ËÌ‰ÂÍÒ ‡‚ÌÓ‚ÂÒÌÓÈ ˆÂÌ˚, Û·./Ã¬Ú.˜","ÃËÌËÏ‡Î¸Ì˚È ËÌ‰ÂÍÒ ‡‚ÌÓ‚ÂÒÌÓÈ ˆÂÌ˚, Û·./Ã¬Ú.˜",Unnamed: 8
0,0,96056.878,1201.07,10323.026,78810.916,139.067,2541.73,720.05,NaN
1,1,94656.491,1114.46,10323.026,77496.079,237.060,1846.86,695.21,NaN
2,2,94296.230,1103.12,10323.026,77216.478,318.612,1780.26,683.75,NaN
3,3,94060.450,1095.66,10323.026,77009.418,353.479,1768.89,679.11,NaN
4,4,95351.188,1135.00,10323.026,78325.012,366.096,1785.26,700.44,NaN

In [32]:
import pandas as pd
import os

# replace with your folder's path
folder_path = r'C:\Users\timas\Downloads\data\2023\nov'

all_files = os.listdir(folder_path)

# Filter out non-CSV files
csv_files = [f for f in all_files if f.endswith('.csv')]

# Create a list to hold the dataframes
df_list = []

csv_files

for csv in csv_files:
    file_path = os.path.join(folder_path, csv)
    try:
        # Try reading the file using default UTF-8 encoding
        df = pd.read_csv(file_path)
        df_list.append(df)
    except UnicodeDecodeError:
        try:
            # If UTF-8 fails, try reading the file using UTF-16 encoding with tab separator
            df = pd.read_csv(file_path, sep=';', encoding='Macintosh')
            df_list.append(df)
        except Exception as e:
            print(f"Could not read file {csv} because of error: {e}")
    except Exception as e:
        print(f"Could not read file {csv} because of error: {e}")

# Concatenate all data into one DataFrame
big_df = pd.concat(df_list, ignore_index=True)

# Save the final result to a new CSV file
big_df.to_csv(os.path.join(folder_path, 'combined_file.csv'), index=False)